version: '3'
services:
  postgres:
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment: 
     POSTGRES_DB: cities_search_development
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: postgres
    ports: 
      - "5432:5432"
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    command: rails s -b 0.0.0.0
    depends_on:
      - postgres
volumes:
  postgres_data: 